### ISSUE TITLE
Is there 1.17.1 support? Can I use it on 1.17.1?

### ISSUE THREAD

**Issue by notdeliable** [trainerlord/worldsystem-depecated#189]
Hi. Is there 1.17.1 support? Can I use it on 1.17.1?

**Comment by trainerlord** [comment]
yes **https://www.spigotmc.org/resources/worldsystem-%E2%97%8F-the-one-world-per-player-solution-%E2%97%8F-gui-%E2%97%8F-highly-configurable-%E2%97%8F-1-8-1-16.49756/download?version=431498**

**Comment by CrazyCloudCraft** [comment]
@trainerlord Issue closed.

**Comment by CrazyCloudCraft** [comment]
@notdeliable
